# Site settings
title: Wysc
email: wyscofficial@icloud.com
description: For students striving to be better, Wysc is the study Discord server that delivers a cohesive, global online studying experience as the premier edu-social cafe based Discord server.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://studywysc.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: wyscofficial
github_username:  coffeebank

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
feed:
  path: /api/feed.xml
permalink: /blog/:year/:title:output_ext

search_enabled: true
search_tokenizer_separator: /[\s/]+/

# Collections
collections:
  api:
    output: true
  css:
    output: true
  docs:
    output: true
    permalink: /docs/:path
  fonts:
    output: true
  joinwsc:
    output: true
  js:
    output: true
  media:
    output: true

destination: _site

include:
  - _headers


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
